import Link from "next/link"
import { Navbar } from "@/components/navbar"
import { Footer } from "@/components/footer"
import { Button } from "@/components/ui/button"
import { 
  QrCode, 
  CheckCircle2,
  Store,
  Smartphone,
  Shield,
  ArrowRight,
  Scan
} from "lucide-react"

const features = [
  {
    title: "Merchant QR Codes",
    description: "Static QR codes for merchants - customers scan to pay any amount.",
    icon: Store
  },
  {
    title: "Customer QR Codes",
    description: "Dynamic QR codes generated by customers for merchants to scan.",
    icon: Smartphone
  },
  {
    title: "Instant Confirmation",
    description: "Real-time payment confirmation for both parties.",
    icon: Scan
  },
  {
    title: "Secure Transactions",
    description: "End-to-end encryption and fraud protection on every payment.",
    icon: Shield
  }
]

export default function QRPaymentPage() {
  return (
    <div className="flex min-h-screen flex-col bg-background">
      <Navbar />
      
      <main className="flex-1">
        {/* Hero Section */}
        <section className="border-b border-border bg-muted/30 py-16 md:py-24">
          <div className="mx-auto max-w-7xl px-4 sm:px-6 lg:px-8">
            <div className="flex flex-col items-center gap-8 lg:flex-row lg:gap-16">
              <div className="flex-1 text-center lg:text-left">
                <div className="mb-6 inline-flex items-center gap-2 rounded-full bg-rose-500/10 px-4 py-2 text-rose-600">
                  <QrCode className="h-5 w-5" />
                  <span className="text-sm font-medium">QR Payment</span>
                </div>
                <h1 className="text-balance text-4xl font-bold tracking-tight text-foreground md:text-5xl">
                  Scan. Pay. Done.
                </h1>
                <p className="mt-6 text-pretty text-lg text-muted-foreground">
                  QR-code based payment system enabling contactless, secure payments at merchant 
                  locations. Simple for customers, efficient for merchants.
                </p>
                <div className="mt-8 flex flex-col gap-4 sm:flex-row sm:justify-center lg:justify-start">
                  <Button size="lg" asChild>
                    <Link href="/participants">For Merchants</Link>
                  </Button>
                  <Button size="lg" variant="outline" asChild>
                    <Link href="/developers">Integration Guide</Link>
                  </Button>
                </div>
              </div>
              <div className="flex-1">
                <div className="aspect-square max-w-md rounded-2xl bg-rose-500/10 p-8">
                  <div className="flex h-full items-center justify-center">
                    <QrCode className="h-48 w-48 text-rose-600/50" />
                  </div>
                </div>
              </div>
            </div>
          </div>
        </section>

        {/* How It Works */}
        <section className="py-16 md:py-24">
          <div className="mx-auto max-w-7xl px-4 sm:px-6 lg:px-8">
            <div className="mx-auto max-w-3xl text-center">
              <h2 className="text-3xl font-bold text-foreground md:text-4xl">How It Works</h2>
              <p className="mt-4 text-lg text-muted-foreground">
                Three simple steps to complete a payment
              </p>
            </div>

            <div className="mt-16 grid gap-8 md:grid-cols-3">
              {[
                {
                  step: "1",
                  title: "Scan",
                  description: "Customer scans the merchant's QR code using their banking or mobile money app."
                },
                {
                  step: "2",
                  title: "Confirm",
                  description: "Enter the payment amount and confirm the transaction details."
                },
                {
                  step: "3",
                  title: "Complete",
                  description: "Payment is processed instantly and both parties receive confirmation."
                }
              ].map((item) => (
                <div key={item.step} className="text-center">
                  <div className="mx-auto mb-4 flex h-16 w-16 items-center justify-center rounded-full bg-primary text-2xl font-bold text-primary-foreground">
                    {item.step}
                  </div>
                  <h3 className="text-xl font-semibold text-foreground">{item.title}</h3>
                  <p className="mt-2 text-muted-foreground">{item.description}</p>
                </div>
              ))}
            </div>
          </div>
        </section>

        {/* Features */}
        <section className="border-y border-border bg-muted/30 py-16 md:py-24">
          <div className="mx-auto max-w-7xl px-4 sm:px-6 lg:px-8">
            <div className="mx-auto max-w-3xl text-center">
              <h2 className="text-3xl font-bold text-foreground md:text-4xl">Features</h2>
              <p className="mt-4 text-lg text-muted-foreground">
                Flexible QR payment options for any scenario
              </p>
            </div>

            <div className="mt-16 grid gap-8 md:grid-cols-2">
              {features.map((feature) => (
                <div key={feature.title} className="rounded-xl border border-border bg-card p-6">
                  <div className="mb-4 inline-flex h-12 w-12 items-center justify-center rounded-lg bg-primary/10">
                    <feature.icon className="h-6 w-6 text-primary" />
                  </div>
                  <h3 className="text-xl font-semibold text-foreground">{feature.title}</h3>
                  <p className="mt-2 text-muted-foreground">{feature.description}</p>
                </div>
              ))}
            </div>
          </div>
        </section>

        {/* For Merchants */}
        <section className="py-16 md:py-24">
          <div className="mx-auto max-w-7xl px-4 sm:px-6 lg:px-8">
            <div className="flex flex-col gap-12 lg:flex-row lg:items-center lg:gap-16">
              <div className="flex-1">
                <h2 className="text-3xl font-bold text-foreground md:text-4xl">For Merchants</h2>
                <p className="mt-4 text-lg text-muted-foreground">
                  Accept payments from any bank or mobile wallet with a simple QR code.
                </p>
                <ul className="mt-8 space-y-4">
                  {[
                    "No expensive POS terminal required",
                    "Accept payments from all banks and wallets",
                    "Instant payment confirmation",
                    "Low transaction fees",
                    "Easy setup - just print your QR code",
                    "Daily settlement to your bank account"
                  ].map((benefit) => (
                    <li key={benefit} className="flex items-start gap-3">
                      <CheckCircle2 className="mt-0.5 h-5 w-5 shrink-0 text-primary" />
                      <span className="text-foreground">{benefit}</span>
                    </li>
                  ))}
                </ul>
                <Button className="mt-8 gap-2" asChild>
                  <Link href="/contact">
                    Register as Merchant
                    <ArrowRight className="h-4 w-4" />
                  </Link>
                </Button>
              </div>
              <div className="flex-1">
                <div className="rounded-xl border border-border bg-card p-8 text-center">
                  <div className="mx-auto mb-6 flex h-48 w-48 items-center justify-center rounded-xl border-2 border-dashed border-border">
                    <QrCode className="h-32 w-32 text-muted-foreground" />
                  </div>
                  <p className="text-lg font-semibold text-foreground">Your Merchant QR Code</p>
                  <p className="mt-2 text-sm text-muted-foreground">
                    Display at your business location for customers to scan
                  </p>
                </div>
              </div>
            </div>
          </div>
        </section>

        {/* CTA */}
        <section className="border-t border-border bg-primary py-16">
          <div className="mx-auto max-w-7xl px-4 text-center sm:px-6 lg:px-8">
            <h2 className="text-3xl font-bold text-primary-foreground md:text-4xl">
              Ready to Go Contactless?
            </h2>
            <p className="mx-auto mt-4 max-w-2xl text-lg text-primary-foreground/80">
              Start accepting QR payments at your business today.
            </p>
            <div className="mt-8 flex flex-col items-center justify-center gap-4 sm:flex-row">
              <Button size="lg" variant="secondary" asChild>
                <Link href="/contact">Get Started</Link>
              </Button>
              <Button size="lg" variant="outline" className="border-primary-foreground/30 text-primary-foreground hover:bg-primary-foreground/10" asChild>
                <Link href="/services">View All Services</Link>
              </Button>
            </div>
          </div>
        </section>
      </main>

      <Footer />
    </div>
  )
}
